### ISSUE TITLE
nestest.log out of date

### ISSUE THREAD

**Issue by quietust** [christopherpow/nes-test-roms#2]
The version of nestest.log in this repository is several revisions out of date:
* March 2013 - fixed a bug in the indirect JMP opcode to correctly preview the actual target address (so that address DBB5 now says "JMP ($02FF) = 0300" instead of "JMP ($02FF) = A900")
* December 2018 - replaced "CYC:x" and "SL:yyy" with "PPU:xxx,yyy" added "CYC:zzz" to indicate the total number of cycles elapsed since reset
* June 2020 - changed "PPU:xxx,yyy" to "PPU:yyy,xxx" (i.e. show scanline first, then pixel number) and fixed CYC so it starts at 7 (since that's how long it takes to reset)

The latest version can be found [here](https://www.qmtpro.com/~nes/misc/nestest.log).

**Comment by massil99** [comment]
The link is down, is there any other way to get the up to date nestest.log, please

**Comment by quietust** [comment]
> The link is down, is there any other way to get the up to date nestest.log, please

Try again - I had an extended power outage last week and when it came back I apparently got a new IPv4 address (which usually almost never happens), and I forgot to update my DNS records.
I can only assume that you're accessing the internet from a device that doesn't have IPv6 properly configured, since I just checked and that's been working fine all along.

**Comment by christopherpow** [comment]
> Try again - I had an extended power outage last week and when it came back I apparently got a new IPv4 address (which usually almost never happens), and I forgot to update my DNS records.
Thanks Q I've updated.
