### ISSUE TITLE
StarsSE demo gets stuck

### ISSUE THREAD

**Issue by michelelorusso05** [christopherpow/nes-test-roms#6]
StarsSE demo softlocks in an endless cycles of interrupts/RTI because of the APU frame interrupts. The ROM should properly handle these interrupts or completely inhibit them by writing to 0x4017 with bit 6 (0x40) set.

**Comment by christopherpow** [comment]
I am not the maintainer of the code found in this repository. I just collected it all in one place.

**Comment by michelelorusso05** [comment]
That's fine then.
